
[Mana]
	#Mana consumption per tick while the halo interface is open
	#Range: > 0
	requestingHaloStaticConsumption = 1
	#Mana consumption when the displayed item list is updated
	#Range: > 0
	requestingHaloUpdateConsumption = 10
	#Mana consumption PER ITEM to extract items from the network
	#Range: > 0
	quantizationExtractConsumption = 20
	#Mana consumption PER ITEM to insert items into the network
	#Range: > 0
	quantizationInsertConsumption = 40
	#The mana capacity of the Quantization Device (recommended to be larger than the per-item quantization costs * 256)
	#Range: > 1
	quantizationDeviceManaCapacity = 100000

[Animations]
	#The animation speed of the quantization of items (that's the ticks of one visual stage, and the full animation time is roughly 2 * <this value>)
	#Range: 1 ~ 100
	quantizationAnimationSpeed = 6

